name: BallGame build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    container:
      image: lxnairx/r-type
    steps:
      - name: Checkout
        uses: actions/Checkout@v4
        with:
          submodules: true

      - name: run cmake
        run: cmake -B build .
      - name: run make
        run: |
          cd build/
          make
