name: BallGame clang-format checker

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check-clang-format:
    name: verify clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Verify Clang-Format version
        run: clang-format --version

      - name: Check clang-format
        run: |
          files=$(find . -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.hpp')
          if [ -n "$files" ]; then
            echo "$files" | xargs clang-format --dry-run --Werror
          else
            echo "::notice ::No files to check."
          fi
